{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common.fullname" . }}
  namespace: apps
spec:
  ingressClassName: {{ .Values.ingress.className | default "kong" }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "common.fullname" . }}
            port:
              number: {{ .Values.service.port | default 80 }}
{{- end }}
