name: Publish Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - "common-microservice/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{
          github.actor }} --password-stdin

      - name: Package and Push Charts go
        run: |
          echo "Processing common-microservice"
          helm package common-microservice
          helm push *.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
          rm *.tgz
